"""
================================================================================
 STAGE 02 · PREPROCESSING
 First Aid Reference Guide (St. John Ambulance Canada) — RAG Pipeline
================================================================================
Cleans the raw Docling text: fixes PDF extraction artifacts, removes
publisher front matter (cover / copyright / TOC), and normalizes structure
(headings, whitespace, duplicated lines).

Usage:
    python 02_preprocessing.py
================================================================================
"""

import os
import re

DATA_DIR = "data"
RAW_TEXT_PATH = os.path.join(DATA_DIR, "raw_docling_text.txt")
CLEANED_TEXT_PATH = os.path.join(DATA_DIR, "cleaned_text.txt")


# ==================================================================
# Fix known PDF broken words
# ==================================================================

def fix_pdf_broken_words(text):
    """
    Fix common PDF extraction artifacts.
    Only fixes known broken words. Does NOT merge normal words.
    """

    replacements = {
        "fi rst": "first",
        "Fi rst": "First",
        "defi brillator": "defibrillator",
        "Defi brillator": "Defibrillator",
        "cardio pulmonary": "cardiopulmonary",
        "blood- borne": "blood-borne",
        "fi rst-aid": "first-aid",
        "emergency scene": "emergency scene",
    }

    for wrong, correct in replacements.items():
        text = text.replace(wrong, correct)

    return text


# ==================================================================
# Document cleaning pipeline
# ==================================================================

def clean_document(text):
    """
    Cleaning pipeline for Docling output.
    Removes PDF artifacts while preserving structure.
    """

    # 1. Normalize line endings
    text = text.replace("\r\n", "\n").replace("\r", "\n")

    # 2. Join hyphenated words split across a line break
    text = re.sub(r'(\w+)-\s*\n\s*(\w+)', r'\1\2', text)

    # 3. Fix known PDF broken words
    text = fix_pdf_broken_words(text)

    # 4. Remove HTML comments generated by Docling
    text = re.sub(r'<!--.*?-->', '', text, flags=re.DOTALL)

    # 5. Remove URLs
    text = re.sub(r'https?://\S+', '', text)

    # 6. Collapse excess whitespace
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


# ==================================================================
# Front matter removal
# ==================================================================
# The First Aid Reference Guide has ~11 pages of cover, funding
# acknowledgement, copyright/ISBN, medical advisory group bios, disclaimer,
# emergency contact card and Table of Contents before the real content
# starts. Chapter 1 is used as a reliable, book-specific anchor.

def remove_front_matter(text):
    """Remove publisher front matter. Keep content starting from Chapter 1."""

    start_pattern = r"#+\s*Chapter\s+1\s+Introduction\s+to\s+First\s+Aid"

    match = re.search(start_pattern, text, flags=re.IGNORECASE)

    if match:
        text = text[match.start():]

    return text.strip()


# ==================================================================
# Structure normalization
# ==================================================================

def normalize_structure(text, headings=None):
    """
    Normalize document structure for RAG.

    - Fixes spacing after hyphens.
    - Separates merged headings from previous text.
    - Removes duplicate consecutive lines.
    - Normalizes whitespace.
    """

    # 1. Fix missing spaces after hyphens
    text = re.sub(r'-(?=[A-Za-z])', '- ', text)

    # 2. Restore headings merged into previous sentence
    if headings:
        headings = sorted(headings, key=len, reverse=True)

        for heading in headings:
            heading = heading.strip()

            if not heading:
                continue

            pattern = r'(?<!\n)' + re.escape(" " + heading)
            text = re.sub(pattern, f"\n\n## {heading}", text)

    # 3. Remove duplicated consecutive lines
    cleaned_lines = []
    previous = ""

    for line in text.splitlines():
        line = line.strip()

        if not line:
            cleaned_lines.append("")
            previous = ""
            continue

        if line == previous:
            continue

        cleaned_lines.append(line)
        previous = line

    text = "\n".join(cleaned_lines)

    # 4. Normalize spaces
    text = re.sub(r'[ \t]+', ' ', text)
    text = re.sub(r'\n{3,}', '\n\n', text)

    return text.strip()


if __name__ == "__main__":

    print("=" * 60)
    print("STAGE 02 · PREPROCESSING")
    print("=" * 60)

    with open(RAW_TEXT_PATH, "r", encoding="utf-8") as f:
        raw_text = f.read()

    cleaned_text = clean_document(raw_text)
    cleaned_text = remove_front_matter(cleaned_text)
    cleaned_text = normalize_structure(cleaned_text)

    print(f"Raw words     : {len(raw_text.split()):,}")
    print(f"Cleaned words : {len(cleaned_text.split()):,}")

    with open(CLEANED_TEXT_PATH, "w", encoding="utf-8") as f:
        f.write(cleaned_text)

    print(f"\nSaved cleaned text -> {CLEANED_TEXT_PATH}")
    print("Done. Next: run 03_chunking.py")
